### ISSUE TITLE
Come on man.

### ISSUE THREAD

**Issue by TFTWPhoenix** [QuadraticKid/KayCeeBee#1]
Can't you atleast give us a bootleg trashy version of KCB?

EDIT: Even mineflayer would do

**Comment by Roizor** [comment]
lol 

_no_


*im no t a kcb devl0per*

**Comment by TFTWPhoenix** [comment]
@Roizor YOU ARE EVERYWHERE WHAT THE HECK

**Comment by QuadraticKid** [comment]
git clone && npm start do it
